# Generated by Django 4.1.4 on 2023-03-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample_app", "0004_remove_celeb_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="celeb",
            name="image",
            field=models.ImageField(default="hfif", upload_to="gallery"),
            preserve_default=False,
        ),
    ]
