# Generated by Django 4.1.4 on 2023-03-30 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sample_app2", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Actors",
            new_name="Actor",
        ),
    ]
