# Generated by Django 4.1.4 on 2023-03-31 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample_app2", "0002_rename_actors_actor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="about",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="actor",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
