# Generated by Django 4.1.4 on 2023-03-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample_app2", "0003_alter_actor_about_alter_actor_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="age",
            field=models.CharField(max_length=3),
        ),
    ]
